name = "spino-gambinocasino-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spino-gambinocasino.fr"
HMAC_KEY = "19b5fbaa66846381b5ea404834ead9d3d895c847701dc188e119ed8121296b91"
COOKIE_NAME = "bl3"
PLAY_PATH = "try-now"
BUTTON_ID = "p224a12a0baee515b8c92ae2d35e08655"
GATE_SALT = "0cfb1309ea149b46"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "v0ae"
CTA_SELECTOR = ".play-button"
